### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by melviso** [rocky/python2-trepan#12]
I'm trying nearly to include trepan as remote debug in pycpp but I've found an issue while parsing the output of info locals: when an array is splitted by length, one comma is missed ... I've navigated through the code but is deep for my time. Any suggerence/patch? An example of what happens:
(you can see how the comma between the segments is not present)

(trepan2*) info locals
data =

  [
  0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1

     0, 1, 0, 1, 0, 1, 0, 0, 1]

n = 33

self = <__main__.ivector object at 0x7fa24d8dbe90>

**Comment by melviso** [comment]
I've attempted to replace with pp locals(), but expasion of the __builtins__ object crashes trepan2 client!

**Comment by rocky** [comment]
Should be fixed by commit 0bd90b3 If so, then close this.
