### ISSUE TITLE
no commands available at the prompt?

### ISSUE THREAD

**Issue by birkenfeld** [rocky/python2-trepan#3]
I wanted to try trepan just now (with the ultimate goal of using it with realgud in Emacs). Installed 0.4.1 with pip on Python 2.7, and ran `trepan2 path/to/script`. It seems that the layer processing debugger commands before passing input to eval as Python is not working:

```
(/home/gbr/devel/nicos-core/bin/nicos-demo:3): <module>
-> 3 import os
(trepan2) c
** NameError: name 'c' is not defined
(trepan2) s
** NameError: name 's' is not defined
(trepan2) q
** NameError: name 'q' is not defined
(trepan2) help
Type help() for interactive help, or help(object) for help about object.
(trepan2) Leaving
```
(The last was Ctrl-D, which did work.)

**Comment by rocky** [comment]
> It seems that the layer processing debugger commands before passing input to eval as Python is not working

A wild guess is that this was installed via pip without the `--egg` option. If that *was* given,  try removing and installing the package using easy_install instead of pip. 

(You probably don't to get me started on the deeper issue behind this here.) 

If neither of these work... 

There should a folder called `trepan/processor/command` wherever trepan2 is installed. And inside that folder should be a file for each command. Specifically, it will start with file `alias.py` and end with file `whatis.py`. Most likely that's there, but the mechanism for reading files in that directory and adding those to the list of commands isn't working.

**Comment by birkenfeld** [comment]
> A wild guess is that this was installed via pip without the --egg option.

Indeed, with `--egg` it appears to work. However, that is not recommended anymore nowadays, and you should make sure that the standard install routine (just pip) works.

At least I would expect an error to pop up if install is done wrongly.

**Comment by rocky** [comment]
> and you should make sure that the standard install routine (just pip) works.

> At least I would expect an error to pop up if install is done wrongly.

Feel free to submit a pull request.

**Comment by birkenfeld** [comment]
Fair enough :)

I assume that `import_relative` is part of the deeper issues. Before I can work on a pull request, I guess I'll need a bit more history behind this state of things, and if it's ok to simplify. (I'm guessing this was necessary to support older versions of Python, but if you only target 2.6 and 2.7 now it might not be anymore.)

**Comment by rocky** [comment]
Yep. `import_relative` is the problem. Feel free to simplify and remove import_relative. Yes this was started back in the Python 2.4 and Python 2.5, and I no longer care about supporting either of those in trepan2. For 2.4 and 2.5 one can use the older pydb.

**Comment by birkenfeld** [comment]
Thanks. I'll see if I can come up with something. Do you want to keep the namespace packages?

**Comment by rocky** [comment]
If I understand namespace packages correctly, *processor* is the only thing that really acts as a namespace package. That is, python files in the *processor* folder are part of the namespace *trepan.processor*. Other than that, I don't care and don't think the code cares.

**Comment by birkenfeld** [comment]
With the PR merged (thanks!) I think this can be closed.
