### ISSUE TITLE
trepan in pytest not working

### ISSUE THREAD

**Issue by diefans** [rocky/python2-trepan#7]
I was trying out trepan in a pytest run with the following exception:

```python-traceback
src/ftr/arangodb/db.py:293: in find
    from trepan.api import debug; debug()       # XXX BREAKPOINT
/home/olli/.virtualenvs/ftr/local/lib/python2.7/site-packages/trepan/api.py:183: in debug
    Mdebugger.debugger_obj = Mdebugger.Debugger(dbg_opts)
/home/olli/.virtualenvs/ftr/local/lib/python2.7/site-packages/trepan/debugger.py:302: in __init__
    Muser.UserInterface(opts=interface_opts))
/home/olli/.virtualenvs/ftr/local/lib/python2.7/site-packages/trepan/interfaces/user.py:48: in __init__
    self.input       = inp or Minput.DebuggerUserInput()
/home/olli/.virtualenvs/ftr/local/lib/python2.7/site-packages/trepan/inout/input.py:41: in __init__
    self.open(self.input, opts)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <trepan.inout.input.DebuggerUserInput object at 0x7ff29215e790>
inp = <_pytest.capture.DontReadFromInput instance at 0x7ff293790e60>, opts = None

    def open(self, inp, opts={}):
        """Use this to set where to read from.
    
            Set opts['try_lineedit'] if you want this input to interact
            with GNU-like readline library. By default, we will assume to
            try importing and using readline. If readline is not
            importable, line editing is not available whether or not
            opts['try_readline'] is set.
    
            Set opts['use_raw'] if input should use Python's use_raw(). If
            however 'inp' is a string and opts['use_raw'] is not set, we
            will assume no raw output. Note that an individual readline
            may override the setting.
            """
        get_option = lambda key: Mmisc.option_set(opts, key,
                                                  self.DEFAULT_OPEN_READ_OPTS)
        if isinstance(inp, types.FileType) or \
           isinstance(inp, StringIO.StringIO):
            self.use_raw = get_option('use_raw')
        elif isinstance(inp, types.StringType):
            if opts is None:
                self.use_raw = False
            else:
                self.use_raw = get_option('use_raw')
                pass
            inp = open(inp, 'r')
        else:
            raise IOError("Invalid input type (%s) for %s" % (type(inp),
>                                                               inp))
E           IOError: Invalid input type (<type 'instance'>) for <_pytest.capture.DontReadFromInput instance at 0x7ff293790e60>
```

**Comment by rocky** [comment]
It looks like what's going on is that pytest has changed stdiinput and by default trepan will open input so you can give it commands.  You can tell trepan were to read from by setting dbg_optsn the debug() call.
For example, somehting like `debug(dbg_opts={'input':''use_raw'}})` . 

I think you can also set the debugger to get input and output via a socket, possibly by setting interface `debug(dbg_opts={'interface': ... })`.  

Try playing around with those options. If you can't figure it out, create the shortest simplest example and that shows the problem. It looks like this shouldn't be hard to do, given what I wrote. 

Create the example, the input you typed and the output you got as a gist. When I get a chance, I'll look at it.

Thanks.

In that code above it also 

I'll guess that pytest does this also for

**Comment by rocky** [comment]
I've started a [pytest plugin for trepan](https://github.com/rocky/pytest-trepan).  It reeds the current pytest development code and version 0.5.1. Post mortem debugging works, but the debugger itself is not finding its commands yet. There may be a number of other rough edges too.

**Comment by rocky** [comment]
[pytest-trepan](https://pypi.python.org/pypi?name=pytest-trepan&:action=display) is now on pypi, so I'll close this.

**Comment by diefans** [comment]
nice work! thanks

**Comment by rocky** [comment]
@diefans Actually, there was a bit of delay because I wanted to have some miniimal test.  I couldn't figure out given the limited time I have how to do that, so in the end I released without tests.

 If you or someone else could add to this, I'd happily put out another release. Once there are tests I think I would be in a better position to get this into the pytest contrib github repository.
